version: '2'
services:

  www:
    build: app/.
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "friend"
       MYSQL_ROOT_PASSWORD: password
    ports:
        - "3306:3306"
